services:
  bedrock:
    image: fingerhutascode/minecraft-bedrock-server:mod-loader-v1
    container_name: minecraft-bedrock-server
    restart: unless-stopped
    environment:
      volumes:
        - /srv/minecraft/lucky-block-race/mods:/home/minecraft/mods:ro
        - ./fetch-world.py:/home/minecraft/fetch-world.py
    network_mode: host
    entrypoint: []
    command: /bin/bash